name: Run Integration Tests

on:
  push:
    branches:
      - master

jobs:
  integration_tests:
    runs-on: macos-latest
    name: Run Integration Tests

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        gem install bundler
        bundle install
    - name: run integration tests for actions
      run: bundle exec fastlane run_action_integration_tests


